#!/bin/bash
#./bash/multiqc2.sh
#bsub -P tct < lys/fastqc.gz ./bash/multiqc2.sh
#BSUB -J multiqc
#BSUB -q general
#BSUB -P tct
#BSUB -o /scratch/projects/tct/lys/multiqcoutputs/output%J.out
#BSUB -e /scratch/projects/tct/lys/multiqcerroroutputs/error%J.err
#BSUB -n 1
#BSUB -B
#BSUB -u l.isma@miami.edu
#BSUB -N

module load java/1.7.0_71
module load fastqc/0.10.1
module load multiqc/v1.14

fastqc /scratch/projects/tct/lys/practicefastqc.gz/*.fastq.gz \
--outdir /scratch/projects/tct/lys/fastqc

cd /scratch/projects/tct/lys/fastqc/
multiqc /scratch/projects/tct/lys/fastqc/*_fastqc \
--outdir /scratch/projects/tct/lys/multiqcoutputs
